x-service-defaults: &service-defaults
  restart: unless-stopped

x-hardened: &hardened
  read_only: true
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

secrets:
  SSH_KEY:
    file: ../common/docker/secrets/backup_rsa

services:
  volume-backup: &volume-backup
    image: ghcr.io/nikarh/docker-volume-backups:main
    container_name: volume-backup
    <<: [*service-defaults, *hardened]
    environment:
      STORAGE_DRIVER: sftp
      SFTP_URL: "ssh://backups@192.168.1.19:2222/data/${DOMAIN}-v2"
      SFTP_PRIVATE_KEY_FILE: /run/secrets/SSH_KEY
      RETENTION_POLICY: count
      RETENTION_COUNT: 3
      BACKUP_CRON: "0 1 * * *"
    volumes:
      - mqtt-certs:/volumes/mqtt-certs:ro
      - mosquitto-data:/volumes/mosquitto-data:ro
      - zigbee2mqtt-data:/volumes/zigbee2mqtt-data:ro
      - hass-data:/volumes/hass-data:ro
      - traefik-data:/volumes/traefik-data:ro
      - authelia-data:/volumes/authelia-data:ro
    secrets:
      - SSH_KEY
    networks:
      - isolated_net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 40M

  restore:
    <<: *volume-backup
    container_name: volume-restore
    restart: on-failure:1
    profiles:
      - restore
    cap_add: ["CHOWN", "FOWNER", "SETGID", "SETUID", "DAC_OVERRIDE"]
    command: ["restore-all"]
    volumes:
      - mqtt-certs:/volumes/mqtt-certs
      - mosquitto-data:/volumes/mosquitto-data
      - zigbee2mqtt-data:/volumes/zigbee2mqtt-data
      - hass-data:/volumes/hass-data
      - traefik-data:/volumes/traefik-data
      - authelia-data:/volumes/authelia-data
