version: "3.8"
x-service-defaults: &service-defaults
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
volumes:
  gitea-data:

services:
  server:
    image: gitea/gitea:1.21.7
    container_name: gitea
    <<: *service-defaults
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`, `git.u8.lv`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.middlewares=authelia@docker,gitea-redirect"
      - "traefik.http.middlewares.gitea-redirect.redirectregex.regex=^https://git\\.u8\\.lv/(.*)"
      - "traefik.http.middlewares.gitea-redirect.redirectregex.replacement=https://git.${DOMAIN}/$$1"
