x-service-defaults: &service-defaults
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
  healthcheck:
    disable: true
secrets:
  IMAP_AUTH:
    file: ./docker/secrets/imap.env
volumes:
  authelia-pam:
  mail-data:
  roundcube-db:
services:
  imapsync:
    image: nikarh/fileserver-imapsync
    container_name: imapsync
    <<: *service-defaults
    environment:
      USERNAME: nikarh
    user: 1000:1000
    volumes:
      - mail-data:/home
    secrets:
      - IMAP_AUTH
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 10M
  dovecot:
    image: dovecot/dovecot:2.3
    container_name: dovecot
    <<: *service-defaults
    volumes:
      - mail-data:/home
      - authelia-pam:/auth
      - /var/lib/docker-services/volumes/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - /var/lib/docker-services/volumes/dovecot/pam-dovecot:/etc/pam.d/dovecot:ro
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 10M
    depends_on:
      init-authelia-pam:
        condition: service_completed_successfully
  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    <<: *service-defaults
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: dovecot
      ROUNDCUBEMAIL_DB_TYPE: sqlite
    volumes:
      - roundcube-db:/var/roundcube/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
      - "traefik.http.routers.roundcube.rule=Host(`mail.${DOMAIN}`) || Host(`mail.u8.lv`)"
      - "traefik.http.routers.roundcube.entrypoints=https"
      - "traefik.http.routers.roundcube.middlewares=authelia@docker"
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M
