version: "3.5"
x-service-defaults: &service-defaults
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
secrets:
  SSH_KEY:
    file: ../common/secrets/backup_rsa
services:
  backup:
    build: ../common/docker/backup
    container_name: backup
    restart: unless-stopped
    << : *service-defaults
    environment:
      BUCKET: ${DOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Volumes to backup
      - mqtt-certs:/volumes/mqtt-certs:ro
      - mosquitto-data:/volumes/mosquitto-data:ro
      - zigbee2mqtt-data:/volumes/zigbee2mqtt-data:ro
      - hass-data:/volumes/hass-data:ro
      - traefik-data:/volumes/traefik-data:ro
      - authelia-data:/volumes/authelia-data:ro
    secrets:
      - SSH_KEY
