version: "3.5"
x-service-defaults: &service-defaults
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
secrets:
  SSH_KEY:
    file: ../common/docker/secrets/backup_rsa
services:
  backup:
    image: nikarh/dotfiles-backup
    container_name: backup
    restart: unless-stopped
    << : *service-defaults
    environment:
      BUCKET: ${DOMAIN}
    volumes:
      # Volumes to backup
    secrets:
      - SSH_KEY
