[theme]
theme = "plain"
[theme.overrides]
separator = ""
idle_bg = "#282A36"
idle_fg = "#738694"
separator_bg = "#282A36"
separator_fg = "#30404D"
warning_bg = "#282A36"
warning_fg = "#D9822B"
critical_bg = "#282A36"
critical_fg= "#A82A2A"
info_bg = "#282A36"
info_fg = "#CED9E0"

[icons]
icons = "awesome4"

[[block]]
block = "pacman"
format = " $icon $pacman.eng(w:1)/$aur.eng(w:1) "
format_up_to_date = " \uf219 "
interval = 3600
aur_command = "yay -Qua"

[[block]]
block = "docker"
interval = 2
format = " $icon $running.eng(w:1)/$total.eng(w:1) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available "
interval = 20
warning = 3.0
alert = 1.0

[[block]]
block = "memory"
format = " $icon $mem_avail "

[[block]]
block = "custom"
interval = 2
format = " $text "
command = "date +\"%a %d %b %R %:::z\""

[[block]]
block = "custom_dbus"
path = "/CurrentKeyboardLayout"