[theme]
name = "plain"
[theme.overrides]
separator = ""
idle_bg = "#282A36"
idle_fg = "#738694"
separator_bg = "#282A36"
separator_fg = "#30404D"
warning_bg = "#282A36"
warning_fg = "#D9822B"
critical_bg = "#282A36"
critical_fg= "#A82A2A"
info_bg = "#282A36"
info_fg = "#CED9E0"

[icons]
name = "awesome"
[icons.overrides]
time = ""

[[block]]
block = "pacman"
format = "{pacman:1}/{aur:1}"
interval = 3600
aur_command = "yay -Qua"

[[block]]
block = "docker"
interval = 2
format = "{running:1}/{total:1}"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
format = "{alias} {available:3}"
unit = "GB"
interval = 20
warning = 3.0
alert = 1.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail:4;G}"
clickable = false

[[block]]
block = "custom"
interval = 2
command = "date +\"%a %d %b %R %:::z\""

[[block]]
block = "custom_dbus"
name = "CurrentKeyboardLayout"
initial_text = "lv"