version: "3.5"
x-logging: &logging
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"
secrets:
  MINIO_ACCESS_KEY:
    file: ./secrets/minio_access_key
  MINIO_SECRET_KEY:
    file: ./secrets/minio_secret_key
services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    restart: unless-stopped
    logging: *logging
    environment:
      AWS_ENDPOINT: minio.files.home.arhipov.net
      AWS_S3_BUCKET_NAME: volume-backup
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/MINIO_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/MINIO_SECRET_KEY
    volumes:
      - /var/lib/service-volumes/volume-backup:/etc/dockervolumebackup/conf.d:ro
      - mqtt-certs:/data/mqtt-certs:ro
      - mqtt-data:/data/mqtt-data:ro
      - zigbee2mqtt-data:/data/zigbee2mqtt-data:ro
      - hass-data:/data/hass-data:ro
      - traefik-data:/data/hass-data:ro
      - authelia-data:/data/hass-data:ro
    secrets:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
