version: "3.5"
x-service-defaults: &service-defaults
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
secrets:
  SSH_KEY:
    file: ../common/docker/secrets/backup_rsa
services:
  backup: &backup
    build: ../common/docker/images/backup
    image: nikarh/backup
    container_name: backup
    << : *service-defaults
    environment:
      BUCKET: ${DOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Volumes to backup
      - mqtt-certs:/volumes/mqtt-certs:ro
      - mosquitto-data:/volumes/mosquitto-data:ro
      - zigbee2mqtt-data:/volumes/zigbee2mqtt-data:ro
      - hass-data:/volumes/hass-data:ro
      - traefik-data:/volumes/traefik-data:ro
      - authelia-data:/volumes/authelia-data:ro
    secrets:
      - SSH_KEY
  restore:
    <<: *backup
    restart: on-failure:1
    profiles: 
      - restore
    container_name: restore
    command: [ "/backup.sh", "restore_all", "${RESTORE_FROM}" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Volumes to backup
      - mqtt-certs:/volumes/mqtt-certs
      - mosquitto-data:/volumes/mosquitto-data
      - zigbee2mqtt-data:/volumes/zigbee2mqtt-data
      - hass-data:/volumes/hass-data
      - traefik-data:/volumes/traefik-data
      - authelia-data:/volumes/authelia-data
