BROWSER=/usr/bin/firefox
TERMINAL="alacritty -e"
EDITOR="nvim"

XDG_CURRENT_DESKTOP=sway
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
XCURSOR_THEME=Dracula-cursor
XCURSOR_SIZE=24
_JAVA_AWT_WM_NONREPARENTING=1