[swipe.commands.three]
left_up = ""
right_up = ""
up = "xdotool key XF86AudioRaiseVolume"
left_down = ""
right_down = ""
down = "xdotool key XF86AudioLowerVolume"
left = ""
right = ""

[swipe.commands.four]
left_up = ""
right_up = "rofi -show calc -modi calc -no-show-match -no-sort"
up = "rofi -combi-modi window,drun -show combi -modi combi"
left_down = ""
right_down = ""
down = "rofi -show run -terminal alacritty -font"
left = ""
right = ""

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false
trigger_on_release = false

[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false