#!/bin/sh

case "$1" in
    pre)
        dbus-send --system --type=signal / org.powertools.Suspend
        ;;
    post)
        dbus-send --system --type=signal / org.powertools.Resume
        ;;
esac
