EDITOR="nvim"
VISUAL="nvim"
TERMINAL="alacritty -e"
BROWSER=/usr/bin/firefox

XDG_CURRENT_DESKTOP=sway

QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt5ct
QT_BEARER_POLL_TIMEOUT=-1

GTK_THEME=Dracula:dark
GTK_ICON_THEME=Dracula

XCURSOR_THEME=Dracula-cursor
XCURSOR_SIZE=24

_JAVA_AWT_WM_NONREPARENTING=1