version: '3.5'
secrets:
  CF_TOKEN:
    file: ./secrets/cf_token
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    logging: &logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 7200 # Checks for updates every two hours
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  traefik-cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: traefik-cloudflare-companion
    restart: unless-stopped
    logging: *logging
    environment:
      TRAEFIK_EXCLUDED_HOST1: home\.arhipov\.net
      TARGET_DOMAIN: home.arhipov.net
      DOMAIN1: arhipov.net
      DOMAIN1_ZONE_ID: 8f927f276e4b3481aba03ee4d29a9ef9
      DOMAIN1_PROXIED: false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    secrets:
      - CF_TOKEN
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    logging: *logging
    ports:
      - '8883:8883'
      - '1883:1883'
    command: >
      sh -c "
        cp /mosquitto/tls/privkey-root.pem /mosquitto/tls/privkey.pem;
        cp /mosquitto/tls/cert-root.pem /mosquitto/tls/cert.pem;
        chown 1883:1883 /mosquitto/tls/*.pem;
        chmod 444 /mosquitto/tls/privkey.pem;
        cp /mosquitto/config/users.conf.unencrypted /mosquitto/config/users.conf
        /usr/bin/mosquitto_passwd -U /mosquitto/config/users.conf;
   
        /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf;
      "
    volumes:
      - /var/lib/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/lib/mosquitto/users.conf:/mosquitto/config/users.conf.unencrypted:ro
      - /var/lib/mosquitto/data:/mosquitto/data
      - /etc/letsencrypt/live/home.arhipov.net-0001/fullchain.pem:/mosquitto/tls/cert-root.pem:ro
      - /etc/letsencrypt/live/home.arhipov.net-0001/privkey.pem:/mosquitto/tls/privkey-root.pem:ro
  samba:
    build: docker/samba
    container_name: samba
    restart: unless-stopped
    logging: *logging
    network_mode: host
    ports:
      - 137:137/udp # nmbd
      - 138:138/udp # nmbd
      - 139:139 # smb over netbios
      - 445:445 # smb over tcp
    entrypoint: /run.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Configs
      - /var/lib/samba/run.sh:/run.sh:ro
      - /var/lib/samba/smb.conf:/etc/samba/smb-base.conf
      # Data
      - /var/data/home:/home
  sftpd:
    image: atmoz/sftp:alpine
    container_name: sftpd
    restart: unless-stopped
    logging: *logging
    ports:
      - '2222:22'
    entrypoint: /run.sh
    volumes:
      # Configs
      - /var/lib/sftpd/secrets/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /var/lib/sftpd/secrets/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - /var/lib/sftpd/sshd_config:/etc/ssh/sshd_config:ro
      - /var/lib/sftpd/run.sh:/run.sh:ro
      - /var/lib/sftpd/authelia.sh:/authelia.sh:ro
      - /var/lib/sftpd/base-auth:/etc/pam.d/base-auth:ro
      # Data
      - /var/data/home:/home
  traefik:
    image: traefik:2.7
    container_name: traefik
    restart: unless-stopped
    logging: *logging
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - "CF_TOKEN"
    environment:
      - "CF_DNS_API_TOKEN_FILE=/run/secrets/CF_TOKEN"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.home.arhipov.net`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=authelia@docker'
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: 1000:1000
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/storage_encryption_key
    volumes:
      - /var/lib/authelia:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.authelia.loadbalancer.server.port=8080'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.home.arhipov.net`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:8080/api/verify?rd=https://authelia.home.arhipov.net'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: '1000:1000'
    volumes:
      - /var/lib/homer:/www/assets
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homer.rule=Host(`home.arhipov.net`)'
      - 'traefik.http.routers.homer.entrypoints=https'
  hass:
    image: homeassistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    logging: *logging
    ports:
      # Apple HomeKit
      - 21064:21064
    devices:
      # Zigbee coordinator
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /dev/serial:/dev/serial
      - /var/lib/hass:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.hass.loadbalancer.server.port=8080'
      - 'traefik.http.routers.hass.rule=Host(`hass.home.arhipov.net`)'
      - 'traefik.http.routers.hass.entrypoints=https'
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    volumes:
      - /var/data/home:/srv
      - /var/lib/filebrowser:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.files.loadbalancer.server.port=8080'
      - 'traefik.http.routers.files.rule=Host(`files.home.arhipov.net`)'
      - 'traefik.http.routers.files.entrypoints=https'
      - 'traefik.http.routers.files.middlewares=authelia@docker'
    command: 
      - "--cache-dir=/data/cache"
      - "-d=/data/filebrowser.db"
      - "-c=/data/filebrowser.json"
      - "-p=8080"
  qbittorrent:
    image: maltyxx/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: 1000:1000
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - /var/lib/qbittorrent/config:/config
      - /var/data/shares/tmp:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.torrents.loadbalancer.server.port=8080'
      - 'traefik.http.routers.torrents.rule=Host(`torrents.files.home.arhipov.net`)'
      - 'traefik.http.routers.torrents.entrypoints=https'
      - 'traefik.http.routers.torrents.middlewares=authelia@docker'
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    logging: *logging
    environment: &arr_env
      PUID: 1000
      PGID: 1000
      TZ: Europe/Riga
    volumes:
      - /var/lib/jackett/config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.jackett.loadbalancer.server.port=9117'
      - 'traefik.http.routers.jackett.rule=Host(`jackett.files.home.arhipov.net`)'
      - 'traefik.http.routers.jackett.entrypoints=https'
      - 'traefik.http.routers.jackett.middlewares=authelia@docker'
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    logging: *logging
    environment: *arr_env
    volumes:
      - /var/lib/radarr/config:/config
      - /var/data/shares/tmp:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.files.home.arhipov.net`)'
      - 'traefik.http.routers.radarr.entrypoints=https'
      - 'traefik.http.routers.radarr.middlewares=authelia@docker'
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    logging: *logging
    environment: *arr_env
    volumes:
      - /var/lib/sonarr/config:/config
      - /var/data/shares/tmp:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
      - 'traefik.http.routers.sonarr.rule=Host(`sonarr.files.home.arhipov.net`)'
      - 'traefik.http.routers.sonarr.entrypoints=https'
      - 'traefik.http.routers.sonarr.middlewares=authelia@docker'
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    logging: *logging
    environment: *arr_env
    volumes:
      - /var/lib/bazarr/config:/config
      - /var/data/shares/tmp:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bazarr.loadbalancer.server.port=6767'
      - 'traefik.http.routers.bazarr.rule=Host(`bazarr.files.home.arhipov.net`)'
      - 'traefik.http.routers.bazarr.entrypoints=https'
      - 'traefik.http.routers.bazarr.middlewares=authelia@docker'
  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    restart: unless-stopped
    logging: *logging
    user: 1000:1000
    environment:
      TZ: Europe/Riga
    volumes:
      - /var/lib/jellyseerr:/app/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.jellyseerr.loadbalancer.server.port=5055'
      - 'traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.files.home.arhipov.net`)'
      - 'traefik.http.routers.jellyseerr.entrypoints=https'
      - 'traefik.http.routers.jellyseerr.middlewares=authelia@docker,jellyheaders'
      - 'traefik.http.middlewares.jellyheaders.headers.customrequestheaders.X-API-Key=MTY1NDcyMzQ0NDI4MDExYmE5MDA4LWE4NTQtNGQ1Mi1hN2FjLWVjZTA3OWRjMDkzZik='
      - 'traefik.http.middlewares.jellyheaders.headers.customrequestheaders.X-API-User=4'
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: '1000:1000'
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      TZ: Europe/Riga
    volumes:
      - /var/lib/syncthing/nikarh:/var/syncthing/config
      - /var/data/shares/nikarh:/var/data/shares/nikarh
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.syncthing.loadbalancer.server.port=8384'
      - 'traefik.http.routers.syncthing.rule=Host(`syncthing.files.home.arhipov.net`)'
      - 'traefik.http.routers.syncthing.entrypoints=https'
      - 'traefik.http.routers.syncthing.middlewares=authelia@docker'
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: 1000:1000
    group_add:
      - "989" # render
      - "985" # video
    ports:
      - 1900:1900/udp # autodiscovery
      - 7359:7359/udp # autodiscovery
    devices:
      - /dev/dri:/dev/dri
    environment:
      JELLYFIN_PublishedServerUrl: https://media.files.home.arhipov.net
    volumes:
      - /var/lib/jellyfin/config:/config:rw
      - /var/lib/jellyfin/cache:/cache:rw
      - /var/data/shares/tmp:/media:ro
      - /var/data/shares/nikarh/Music:/music
      - /var/data/shares/nikarh/Videos:/nikarh/videos
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
      - 'traefik.http.routers.jellyfin.rule=Host(`media.files.home.arhipov.net`)'
      - 'traefik.http.routers.jellyfin.entrypoints=https'
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    user: "1000:1000"
    environment:
      PHOTOPRISM_ORIGINALS_LIMIT: 1000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "true"                      # No authentication required (disables password protection)
      PHOTOPRISM_SPONSOR: "true"
      PHOTOPRISM_READONLY: "true"                    # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "true"                # Enables experimental featuress
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a servers
      PHOTOPRISM_DATABASE_DSN: "/photoprism/database/db.sqlite"
      PHOTOPRISM_SITE_URL: "https://photos.files.home.arhipov.net/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "Photos"
      PHOTOPRISM_SITE_CAPTION: "My photos"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
    volumes:
      - /var/data/shares/nikarh/Pictures:/photoprism/originals:ro
      - /var/lib/photoprism/import:/photoprism/import
      - /var/lib/photoprism/storage:/photoprism/storage
      - /var/lib/photoprism/database:/photoprism/database
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.photoprism.loadbalancer.server.port=2342'
      - 'traefik.http.routers.photoprism.rule=Host(`photos.files.home.arhipov.net`)'
      - 'traefik.http.routers.photoprism.entrypoints=https'
      - 'traefik.http.routers.photoprism.middlewares=authelia@docker'
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata
    restart: unless-stopped
    logging: *logging
    healthcheck:
      disable: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      DISABLE_TELEMETRY: 1
      DOCKER_USR: 1000
      DOCKER_GRP: 1000
    volumes:
      - /var/lib/netdata/config:/etc/netdata
      - /var/lib/netdata/lib:/var/lib/netdata
      - /var/lib/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.netdata.loadbalancer.server.port=19999'
      - 'traefik.http.routers.netdata.rule=Host(`netdata.files.home.arhipov.net`)'
      - 'traefik.http.routers.netdata.entrypoints=https'
      - 'traefik.http.routers.netdata.middlewares=authelia@docker'