version: '3.5'

services:
  sftpd:
    image: atmoz/sftp
    container_name: sftpd
    restart: unless-stopped
    ports:
      - '2222:22'
    volumes:
      - /etc/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - /etc/sftp/users.conf:/etc/sftp/users.conf:ro
      - /var/data/shares/tmp:/home/tmp/tmp
      - /home/files/data:/home/tmp/ssd
      - /var/data/shares/nikarh:/home/nikarh/data
      - /var/data/shares/nikarh/TKM:/home/trendkillmethod/TKM
      - /var/data/shares/tmp:/home/nikarh/tmp
      - /var/data/shares/alyonovik:/home/alyonovik/data
      - /var/data/shares/tmp:/home/alyonovik/tmp
  hass:
    image: homeassistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    ports:
      - '127.0.0.1:25001:8080'
    volumes:
      - /var/lib/hass:/config
      - /etc/localtime:/etc/localtime:ro
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: '1000:1000'
    command: 
      - "--cache-dir=/data/cache"
      - "-d=/data/filebrowser.db"
      - "-c=/data/filebrowser.json"
      - "-p=8080"
    ports:
      - '127.0.0.1:25002:8080'
    volumes:
      - /var/data/shares/nikarh:/srv/nikarh/data
      - /var/data/shares/tmp:/srv/nikarh/tmp
      - /var/data/shares/alyonovik:/srv/alyonovik/data
      - /var/data/shares/tmp:/srv/alyonovik/tmp
      - /var/lib/filebrowser:/data
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "127.0.0.1:25003:4533"
    volumes:
      - "/var/lib/navidrome:/data"
      - "/var/data/shares/nikarh/Music:/music:ro"
  qbittorrent:
    image: maltyxx/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ=Europe/Riga
      - QBITTORRENT_UID=1000
      - QBITTORRENT_GID=1000
    ports:
      - 127.0.0.1:25004:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - /var/lib/qbittorrent/config:/qbittorrent/config
      - /var/lib/qbittorrent/data/:/qbittorrent/data
      - /var/data/shares/tmp:/downloads
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    user: '1000:1000'
    environment:
      - TZ=Europe/Riga
    volumes:
      - /var/lib/syncthing/nikarh:/var/syncthing/config
      - /var/data/shares/nikarh:/var/data/shares/nikarh
    ports:
      - 127.0.0.1:25005:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 7200 # Checks for updates every two hours
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"