version: '3.5'
services:
  nextcloud-db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/files/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    user: 1000:1000
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    links:
      - nextcloud-db
    ports:
      - 25050:80
    volumes:
      - /home/files/nextcloud/data:/var/www/html
      - /var/data/shares/nikarh:/var/www/html/data/nikarh/files/data:ro
      - /var/data/shares/tmp:/var/www/html/data/nikarh/files/tmp:ro
    environment:
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db