#!/bin/bash

alias ls='ls --color=auto'
alias l='ls -lAh'
alias df='df -h'
alias less='less -r'

if type -P eza > /dev/null; then
    alias ls='eza --icons'
    alias l='eza --icons -la'
    alias e='eza --icons: -la'
fi

alias zx='zi'
alias lk='lazygit'
