#!/bin/bash

alias ls='ls --color=auto'
alias l='ls -lAh'
alias df='df -h'
alias less='less -r'

if type -P eza > /dev/null; then
    alias ls='eza'
    alias l='eza -la'
    alias e='eza -la'
fi

if type -P lsd > /dev/null; then
    alias ls='lsd'
    alias l='lsd -la'
fi

alias zx='zi'
alias lk='lazygit'
